spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 2000
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: select 'x'
    filters: stat
    #redis配置
  redis:
    host: 192.168.1.
    port: 6379
    password:
    timeout: 1000
    poll:
      max-active: 2048
      max-wait: -1
      max-idle: 200
